Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var
A,B,C,R : Real
Inicio

Escreva("Digite 1ºValor")
Leia (A)
Escreva("Digite 2ºValor")
leia (B)
Escreva("Digite 3ºValor")
Leia(C)
R<-(A+B-C)
Escreva("Resultado é ", R)


Fimalgoritmo