Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2024
Var
A,C,L,Z : Real

Inicio
Escreva("Digite o 1ºValor")
Leia(A)
Escreva("Digite o 2ºValor")
Leia(C)
Escreva("Digite o 3ºValor")
Leia(L)
Z<-(L+A*2)/C
Escreval("Resultado é",Z)
Escreva("Parabéns :) ")
Fimalgoritmo